name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.8
  - idna=2.9
  - ld_impl_linux-64=2.34
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgomp=9.2.0
  - libstdcxx-ng=9.2.0
  - ncurses=6.2
  - openssl=1.1.1f
  - pip=20.0.2
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.2
  - python_abi=3.8
  - readline=8.0
  - requests=2.23.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.10
  - urllib3=1.25.7
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11

